name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    
    env:
      MAIN_PY_FILE: 'ScreenText.py'  # Define the path to your main.py file here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./
    
    - name: Install pywin32 only for Windows
      if: matrix.os == 'windows-latest'
      run: |
        pip install pywin32==306 py2exe==0.13.0.0

    - name: Install PyInstaller
      run: |
        pip install pyinstaller
      working-directory: ./

    - name: Build executable for ${{ matrix.os }}
      run: |
        python ${{ env.MAIN_PY_FILE }}
      working-directory: ./
    
    - name: Rename builded app
      run: mv ./dist ./dist-${{ matrix.os }}
    
    - name: Upload result job ${{ matrix.os }}
      uses: actions/upload-artifact@v3
      with:
        name: screentext-pyinstaller-artifact
        path: ./dist*
  
  release:
    name: Upload Release Asset Windows
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download release asset
      uses: actions/download-artifact@v2
      with:
        name: screentext-pyinstaller-artifact
        path: ./dist*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ScreenText_Token }}
      with:
        tag_name: v1.0.2
        release_name: Release v1.0.2 Containing Windows, Linux and MacOS Executables with minor bug fixes
        draft: false
        prerelease: false
    
    - name: Upload Release Asset Windows
      id: upload-release-asset-windwos
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ScreenText_Token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist*/dist-windows-latest/ScreenText.exe
        asset_name: ScreenText-Windows.exe
        asset_content_type: application/octet-stream
    
    - name: Upload Release Asset Linux
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ScreenText_Token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist*/dist-ubuntu-latest/ScreenText
        asset_name: ScreenText-Linux
        asset_content_type: application/octet-stream
    
    - name: Upload Release Asset MacOS
      id: upload-release-asset-macos
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ScreenText_Token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist*/dist-macos-latest/ScreenText
        asset_name: ScreenText-MacOS
        asset_content_type: application/octet-stream